### ISSUE TITLE
How to run when only the docker version of foldseek-gpu is available?

### ISSUE THREAD

**Issue by Dx-wmc** [steineggerlab/unicore#2]
Hi, since I cannot directly install the GPU version of foldseek, as pointed out in this issue [#285](https://github.com/steineggerlab/foldseek/issues/285) . Therefore, I can only build the Docker version. In this case, how can I use Unicore?

**Comment by endixk** [comment]
We have included a Python script of ProstT5 encoder running with `pytorch`, which doesn't require Foldseek-GPU. This is currently used in default for `createdb` module.

`easy-core` workflow currently has an issue of not being able to utilize this Python script, which we will fix very soon.

**Comment by Dx-wmc** [comment]
Thank you for your explanation, but I encountered an error when running the PyTorch version.  
I don't know what went wrong. The command I used is: `unicore createdb tt tt/db prostt5/weights -g -o --threads 30`
```
############# STATS #############
Total number of predictions: 7
Total time: 7.48[s]; time/prot: 1.0685[s]; avg. len= 372.43
Writing results now to disk ...
Finished writing results to /home/unicore/tt/combined_3di.fasta
Finished writing probabilities to /home/unicore/tt/output_probabilities.csv
createdb /home/unicore/tt/combined_aa.fasta tt/db --shuffle 0 

MMseqs Version:       	9.427df8a
Database type         	0
Shuffle input database	false
Createdb mode         	0
Write lookup file     	1
Offset of numeric ids 	0
Compressed            	0
Verbosity             	3

Converting sequences

Time for merging to db_h: 0h 0m 0s 0ms
Time for merging to db: 0h 0m 0s 0ms
Database type: Aminoacid
Time for processing: 0h 0m 0s 40ms
createdb /home/unicore/tt/combined_3di.fasta /home/unicore/tt/db_ss --shuffle 0 

MMseqs Version:       	9.427df8a
Database type         	0
Shuffle input database	false
Createdb mode         	0
Write lookup file     	1
Offset of numeric ids 	0
Compressed            	0
Verbosity             	3

Converting sequences

Time for merging to db_ss_h: 0h 0m 0s 0ms
Time for merging to db_ss: 0h 0m 0s 0ms
Database type: Aminoacid
Time for processing: 0h 0m 0s 19ms
Error: No such file or directory (os error 2)
```

**Comment by endixk** [comment]
This is a minor error and you can proceed with the subsequent analyses (please refer to #1). We will soon release a new version with this behavior fixed.

**Comment by Dx-wmc** [comment]
Looking forward to the new version.
